### ISSUE TITLE
Case-folding ß becomes ss

### ISSUE THREAD

**Issue by synesthesiam** [home-assistant/hassil#37]
Issue for https://github.com/home-assistant/intents/issues/1133

Hassil normalizes text before matching with `casefold`, but this will expand "ß" to "ss" in German.

A copy of the original text should be kept, and some method for tracking the correspondence between the original and normalized texts is needed.

**Comment by mib1185** [comment]
it seems that only the response text is normlized, because the `slot.name` is correct 🤔 
```
$ python3 -m script.intentfest parse --language de --sentence 'wie ist die Außentemperatur?'
{
  "text": "wie ist die Außentemperatur?",
  "match": true,
  "intent": "HassGetState",
  "slots": {
    "name": "Außentemperatur"
  },
  "context": {
    "domain": "sensor",
    "unit_of_measurement": "°C"
  },
  "response_key": "einzeln",
  "response": "Aussentemperatur ist 21 °C"
}
```

**Comment by mib1185** [comment]
or is the `slot.name` evaluated before any matching occur?

**Comment by synesthesiam** [comment]
hassil 2.0 no longer case folds
